drop table if exists t_meeting_uploaded_file;
drop table if exists t_meeting_operation_log;
drop table if exists t_meeting_notification;
drop table if exists t_meeting_attendee;
drop table if exists t_meeting_topic;
drop table if exists t_meeting_main;
drop table if exists t_meeting_authority;
drop table if exists t_wxdept_users;
drop table if exists t_wxdept;

create table t_wxdept (
    f_dept_id varchar(700) primary key,
    f_dept_nm varchar(500) not null,
    f_order_index integer,
    f_parent_dept_id varchar(700),
    f_create_time timestamp default now(),
    f_pathids varchar(2000),
    f_pathnames varchar(2000),
    f_tel varchar(100),
    f_deptnm_alias varchar(500)
);

create table t_wxdept_users (
    f_user_id varchar(500) primary key,
    f_user_name varchar(500) not null,
    f_dept_id varchar(700),
    f_phone varchar(100),
    f_create_time timestamp default now(),
    f_isleader varchar(10),
    f_position varchar(200),
    f_email varchar(200),
    f_gender varchar(10),
    f_avatar varchar(1000),
    f_english_name varchar(200),
    f_status varchar(20),
    f_qr_code varchar(1000),
    f_telephone varchar(100),
    f_isQianWei varchar(10),
    f_center_id varchar(100),
    f_xndept_id varchar(100),
    f_desc varchar(1000),
    f_emp_typ varchar(50),
    f_emp_status varchar(50),
    f_tb varchar(50),
    f_tags varchar(1000),
    f_enable varchar(10),
    needauth_user varchar(10),
    needauth_dept varchar(10),
    needauth_tag varchar(10)
);

create table t_meeting_authority (
    id bigint generated by default as identity primary key,
    user_id varchar(500) not null,
    user_name varchar(500) not null,
    dept_id varchar(700),
    authority smallint not null,
    group_code varchar(100) not null default 'DEFAULT',
    create_time timestamp not null default now(),
    unique(user_id, dept_id, group_code)
);

create table t_meeting_main (
    id bigint generated by default as identity primary key,
    meeting_date varchar(50) not null,
    meeting_time varchar(50) not null,
    period_no varchar(100),
    location varchar(500),
    leaders varchar(1000),
    content varchar(2000),
    status varchar(32) not null default 'DRAFT',
    creater varchar(500),
    created_time timestamp not null default now(),
    updated_time timestamp not null default now()
);

create table t_meeting_topic (
    id bigint generated by default as identity primary key,
    meeting_id bigint not null,
    topic_type varchar(100),
    title varchar(1000) not null,
    report_dept_id varchar(2000),
    report_dept_name varchar(2000),
    participant_dept_id varchar(2000),
    participant_dept_name varchar(2000),
    summary varchar(4000),
    sort_no integer not null default 1,
    status varchar(32) not null default 'WAITING',
    start_time timestamp,
    end_time timestamp,
    actual_minutes integer,
    conclusion varchar(4000),
    notice varchar(2000),
    project_code varchar(200),
    report_dept_signed smallint not null default 0,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),
    foreign key(meeting_id) references t_meeting_main(id) on delete cascade
);

create table t_meeting_attendee (
    id bigint generated by default as identity primary key,
    meeting_id bigint not null,
    topic_id bigint not null,
    user_id varchar(500) not null,
    user_name varchar(500) not null,
    attendee_type varchar(32) not null,
    selected_by varchar(500),
    selected_source varchar(32) not null,
    selected_dept_id varchar(500),
    created_at timestamp not null default now(),
    confirm_status varchar(32) not null default 'PENDING',
    confirmed_by varchar(500),
    confirmed_at timestamp,
    sign_status varchar(32) not null default 'UNSIGNED',
    signed_at timestamp,
    unique(topic_id, user_id, attendee_type),
    foreign key(meeting_id) references t_meeting_main(id) on delete cascade,
    foreign key(topic_id) references t_meeting_topic(id) on delete cascade
);

create table t_meeting_notification (
    id bigint generated by default as identity primary key,
    meeting_id bigint,
    topic_id bigint,
    title varchar(500) not null,
    msg_body varchar(4000),
    tousers varchar(4000),
    send_time timestamp,
    job_id varchar(200),
    created_at timestamp not null default now()
);

create table t_meeting_operation_log (
    id bigint generated by default as identity primary key,
    meeting_id bigint,
    topic_id bigint,
    operation_type varchar(64) not null,
    operation_name varchar(100) not null,
    operator_id varchar(500),
    operator_name varchar(500),
    operator_role varchar(32),
    operator_dept_id varchar(700),
    operator_dept_name varchar(500),
    target_user_ids varchar(4000),
    target_user_names varchar(4000),
    target_dept_ids varchar(4000),
    target_dept_names varchar(4000),
    operation_content varchar(4000),
    created_at timestamp not null default now()
);

create table t_meeting_uploaded_file (
    id bigint generated by default as identity primary key,
    meeting_id bigint,
    file_name varchar(500),
    file_size bigint,
    parser_status varchar(32),
    parser_message varchar(1000),
    created_at timestamp not null default now()
);

create index idx_meeting_topic_meeting on t_meeting_topic(meeting_id, sort_no);
create index idx_attendee_meeting on t_meeting_attendee(meeting_id);
create index idx_attendee_user on t_meeting_attendee(user_id, sign_status);
create index idx_attendee_confirm on t_meeting_attendee(user_id, confirm_status);
create index idx_notice_meeting on t_meeting_notification(meeting_id);
create index idx_authority_group_user on t_meeting_authority(group_code, user_id);
create index idx_operation_meeting on t_meeting_operation_log(meeting_id, created_at);
create index idx_operation_topic on t_meeting_operation_log(topic_id, created_at);
create index idx_operation_operator on t_meeting_operation_log(operator_id, created_at);
create index idx_operation_type on t_meeting_operation_log(operation_type, created_at);


