spring:
  datasource:
    driver-class-name: com.kingbase8.Driver
    url: jdbc:kingbase8://127.0.0.1:54321/meeting_management
    username: system
    password: kingbase

mybatis:
  configuration:
    map-underscore-to-camel-case: true
